describe('MyCenter- Center Information Menu', () => {
    beforeEach(() => {
        cy.viewport(1280, 960)
        cy.login("testdirector1@smart.care", "passistheword")
        cy.wait(1500)
    })

    afterEach(() => {
        cy.logout({ multiple: true})
        cy.wait(1500)
    })

    it('Edit Center Information',  () => {
        cy.viewport(1280, 960)
        cy.get(myCenter).click()
        cy.contains('Center Information')
        // cy.get(centerName).click().type('smartCare Live TestCenter 1')
        cy.get(centerPhone).click().type('1111111111')
        // cy.get(centerAddress).click().type('10819 Street')
        // cy.get(centerCity).click().type('NY')
        // cy.get(centerZip).click().type('11111')
        cy.get(centerSaveInfo).click()
        cy.get(families).should('be.visible').click()
    }) 

    it('Add locations/Rooms, then delete it',  () => {
        cy.viewport(1280, 960)
        cy.get(myCenter).click()
        cy.contains('Center Information')
        cy.get(centerInfo).click()
        cy.get(centerLocations).click()
        cy.wait(2000)

        cy.get(addLocation).click()
        cy.get(locationName).type('TestLocation')
        cy.get(locationType).click()
        cy.get(locationSpace).click()
        cy.wait(2000)
        cy.get(locationType).click()
        cy.get(locationRoom).click()
        cy.get(locationCapacity1).click().type('9')
        cy.get(locationDescription).type('DescriptionTest')
        cy.get(locationSave).click()
        cy.wait(2000)
        cy.get(locationSearch).type('TestLocation')
        cy.wait(3000)
        cy.get(locationDelete).click()
        cy.get(confirmDeleteLocation).click()
        cy.get(locationDelete).click()
        cy.get(confirmDeleteLocation).click()
        cy.get(families).should('be.visible').click()
    }) 

    // it('Add a class, search it and delete it',  () => {
    //     cy.viewport(1280, 960)
    //     cy.get(myCenter).click()
    //     cy.contains('Center Information')
    //     cy.get(centerInfo).click()
    //     cy.get(centerClasses).click()
    //     cy.get(add).click()
    //     cy.get(className).type('ClassTest')
    //     cy.get(classRoom).click()
    //     cy.wait(2000)
    //     cy.get(classRoom3).click()
    //     cy.get(classStartAge).type('3')
    //     cy.get(classEndAge).type('19')
    //     cy.get(classTeachersRatio).type('3')
    //     cy.get(classChildrenRatio).type('15')
    //     cy.get(classEndYear).click()
    //     cy.get(classDesiredT).type('5')
    //     cy.get(classDesiredC).type('15')
    //     cy.get(classSize).type('20')
    //     cy.get(classSave).click()
    //     cy.wait(2000)
    //     cy.get(searchClass).click().type('ClassTest')
    //     cy.get(deleteClass).click()
    //     cy.get(confirmDeleteClass).click()
    // }) 

    it('Add a schools and delete it',  () => {
        cy.viewport(1280, 960)
        cy.get(myCenter).click()
        cy.contains('Center Information')
        cy.get(centerInfo).click()
        cy.get(centerSchool).click()
        cy.get(addSchool).click()
        cy.get(schoolName).type('TestSchool')
        cy.get(schoolSave).click()
        cy.get(schoolSearch).type('TestSchool')
        cy.get(schoolDelete).click()
        cy.get(schoolDeleteConfirm).click()
    }) 

    it('Meals',  () => {
        cy.viewport(1280, 960)
        cy.get(myCenter).click()
        cy.contains('Center Information')
        cy.get(centerInfo).click()
        cy.get(centerMeals).click()
        cy.contains('Breakfast')
        cy.contains('AM Snack')
        cy.contains('Lunch')
        cy.contains('PM Snack')
        cy.contains('Dinner')
    }) 

    it('Templates- add and delete with if-else',  () => {
        cy.viewport(1280, 960)
        cy.get(myCenter).click()
        cy.contains('Center Information')
        cy.get(centerInfo).click()
        cy.get(centerTemplates).click()
        cy.wait(1500)
        cy.get(body).then(body => {
            if (body.find(".no-record").length > 0) {   
                cy.get(add).click()
                cy.get(templateName).type('NameTest')
                cy.get(templateParentCategory).type('Parent Category test')
                cy.get(templateCategory).type('Category Test')
                cy.get(templateBold).click()
                cy.get(templateContent).type('Content Test')
                cy.get(templateSave).click()
                cy.wait(2000)
                cy.get(templateDelete).click()
                cy.get(templateConfirm).click()
            }else {
                cy.get(templateDelete).click()
                cy.get(templateConfirm).click()
                cy.wait(2000)
            }
        });
        
     })

        it('Settings',  () => {
            cy.viewport(1280, 960)
            cy.get(myCenter).click()
            cy.contains('Center Information')
            cy.get(centerInfo).click()
            cy.get(centerSettings).click()
            cy.get(settingsCheck1).click()

            cy.get(settingsCheck2).click()
            cy.get(settingsCheck4).click()
            cy.get(settingsCheck5).click()
            cy.get(settingsCheck6).click()
            cy.get(settingsCheck7).click()
            cy.contains('Center Settings successfully updated').should('be.visible')
            cy.wait(2000)
            cy.get(families).should('be.visible').click()
            cy.get(myCenter).click()
            cy.get(centerInfo).click()
            cy.get(centerSettings).click()
            cy.get(settingsCheck1).click()
            cy.get(settingsCheck2).click()
            cy.get(settingsCheck4).click()
            cy.get(settingsCheck5).click()

            cy.get(settingsCheck6).click()
            cy.get(settingsCheck7).click()
            cy.contains('Center Settings successfully updated').should('be.visible')
            cy.wait(2000)
   
        }) 

        it('Custom Fields',  () => {
            cy.viewport(1280, 960)
            cy.get(myCenter).click()
            cy.get(centerInfo).click()
            cy.get(centerTags).click()
            cy.wait(2000)
            cy.get(bodyTags).then(bodyTags => {
                if (bodyTags.find(".no-record").length > 0) {   
                    cy.get(add).click()
                    
                }else {
                    cy.get(centerInfo).click()
                    cy.get(centerTags).click()
                    
                }
            });
            
    }) 

})




//CENTER INFORMATION
const families = ('body > sc-app-root > sc-center > sc-app-layout > div > aside > div > sc-nav-item:nth-child(4) > div > span.icon.ng-star-inserted')
const myCenter = ('body > sc-app-root > sc-center > sc-app-layout > div > aside > div > sc-nav-item:nth-child(11) > div > span.icon.ng-star-inserted')
const centerName = ('.mat-form-field.ng-tns-c64-41 > .mat-form-field-wrapper > .mat-form-field-flex')
const centerPhone = ('.ng-pristine >  mat-form-field:nth-child(3) > .mat-form-field-wrapper > .mat-form-field-flex')
const centerAddress = ('.address > .mat-form-field-wrapper > .mat-form-field-flex')
const centerCity = ('.mat-form-field.ng-tns-c64-44 > .mat-form-field-wrapper > .mat-form-field-flex')
const centerState = ('.mat-form-field.ng-tns-c64-45 > .mat-form-field-wrapper > .mat-form-field-flex')
const centerZip = ('.mat-form-field.ng-tns-c64-45 > .mat-form-field-wrapper > .mat-form-field-flex')
const centerTax = ('.mat-form-field.ng-tns-c64-47 > .mat-form-field-wrapper > .mat-form-field-flex')
const centerSaveInfo = ('button')
const centerInfo = ('sc-nav-group > .active')
const centerLocations = ('.mat-menu-content > :nth-child(2) > .item')
const addLocation = ('.table-actions > .secondary > button')
const locationName = ('.mat-focused > .mat-form-field-wrapper > .mat-form-field-flex')
const locationType = ('.mat-form-field-type-mat-select > .mat-form-field-wrapper > .mat-form-field-flex')
const locationRoom = ('.mat-option:nth-child(1)')
const locationSpace = ('.mat-option:nth-child(2)')
const locationCapacity1 = ('.mat-form-field.ng-tns-c64-56 > .mat-form-field-wrapper > .mat-form-field-flex')
const locationDescription = ('.mat-form-field.ng-tns-c64-54 > .mat-form-field-wrapper > .mat-form-field-flex')
const locationSave = (':nth-child(2) > button')
const locationSearch =('.mat-form-field-flex')
const locationDelete = (':nth-child(1) > .cdk-column-actions > sc-actions-cell > .secondary > button')
const confirmDeleteLocation = (':nth-child(2) > button')

const centerClasses = ('.mat-menu-content > :nth-child(3) > .item')
const add = ('button')
const className = ('.ng-pristine > .mat-form-field:nth-child(1) > .mat-form-field-wrapper > .mat-form-field-flex')
const classRoom = ('.two-columns > .mat-form-field:nth-child(3) > .mat-form-field-wrapper > .mat-form-field-flex ')
const classRoom3 = ('#mat-option-54 > .mat-option-text')
const classStartAge = (':nth-child(4) > .mat-form-field > .mat-form-field-wrapper > .mat-form-field-flex')
const classEndAge = (':nth-child(5) > .mat-form-field > .mat-form-field-wrapper > .mat-form-field-flex')
const classEndYear = (':nth-child(4) > .ng-untouched > :nth-child(3) > button')
const classTeachersRatio = ('.mat-form-field.ng-tns-c64-56 > .mat-form-field-wrapper > .mat-form-field-flex')
const classChildrenRatio = ('.mat-form-field.ng-tns-c64-57 > .mat-form-field-wrapper > .mat-form-field-flex')
const classSize = ('.mat-form-field.ng-tns-c64-60 > .mat-form-field-wrapper > .mat-form-field-flex')
const classDesiredT = ('.mat-form-field.ng-tns-c64-58 > .mat-form-field-wrapper > .mat-form-field-flex')
const classDesiredC = ('.mat-form-field.ng-tns-c64-59 > .mat-form-field-wrapper > .mat-form-field-flex')
const classSave = ('.mat-dialog-actions > :nth-child(2) > button')
const searchClass = ('.mat-form-field-flex')
const deleteClass = (':nth-child(1) > .cdk-column-actions > sc-actions-cell > .secondary > button')
const confirmDeleteClass = (':nth-child(2) > button')

const centerSchool =('.mat-menu-content > :nth-child(4) > .item')
const addSchool = ('body > sc-app-root > sc-center > sc-app-layout > div > section > sc-center-settings > section > sc-center-schools > sc-table-wrapper > div > div > sc-button > button')
const schoolName = ('#mat-dialog-0 > sc-edit-center-school > mat-dialog-content > form > mat-form-field > div > div.mat-form-field-flex.ng-tns-c64-51 > div')
const schoolSave = ('#mat-dialog-0 > sc-edit-center-school > mat-dialog-actions > sc-button:nth-child(2) > button')
const schoolSearch = ('body > sc-app-root > sc-center > sc-app-layout > div > section > sc-center-settings > section > sc-center-schools > sc-table-wrapper > div > sc-filtered-list-search > mat-form-field > div > div.mat-form-field-flex.ng-tns-c64-49')
const schoolDelete = ('body > sc-app-root > sc-center > sc-app-layout > div > section > sc-center-settings > section > sc-center-schools > sc-table-wrapper > table > tbody > tr:nth-child(1) > td.mat-cell.cdk-cell.cdk-column-actions.mat-column-actions.ng-star-inserted > sc-actions-cell > sc-button > button')
const schoolDeleteConfirm = ('#mat-dialog-1 > sc-simple-dialog > mat-dialog-actions > sc-button:nth-child(2) > button')

const centerMeals = ('.mat-menu-content > :nth-child(5) > .item')

const centerTemplates = ('#mat-menu-panel-3 > div > sc-nav-item:nth-child(6) > div > span.name.ellipsis.ng-star-inserted')
const addTemplate = ('body > sc-app-root > sc-center > sc-app-layout > div > section > sc-center-settings > section > sc-templates > div > sc-table-wrapper > div > div > sc-button > button')
const body = ('body > sc-app-root > sc-center > sc-app-layout > div > section')
const templateName = ('form.ng-pristine > .mat-form-field-appearance-standard > .mat-form-field-wrapper > .mat-form-field-flex')
const templateParentCategory = ('.mat-form-field:nth-child(2) > .mat-form-field-wrapper > .mat-form-field-flex')
const templateCategory = ('.mat-form-field:nth-child(3) > .mat-form-field-wrapper > .mat-form-field-flex')
const templateBold = ('.note-icon-bold')
const templateContent = ('.note-editable')
const templateSave = ('.actions > :nth-child(1) > button')
const templateDelete = ('sc-actions-cell > .secondary > button')
const templateConfirm = (':nth-child(2) > button')

const centerSettings = ('.mat-menu-content > :nth-child(7) > .item')
const settingsCheck1 = ('.ng-untouched > .ng-star-inserted:nth-child(1) > .mat-checkbox')
const settingsCheck2 = ('.ng-untouched > .ng-star-inserted:nth-child(2) > .mat-checkbox:nth-child(2)')
const settingsCheck4 = ('.ng-star-inserted:nth-child(2) > .mat-checkbox:nth-child(4)')
const settingsCheck5 = ('.ng-star-inserted:nth-child(3) > .mat-checkbox')
const settingsCheck6 = ('.ng-star-inserted:nth-child(4) > .mat-checkbox')
const settingsCheck7 = ('.ng-star-inserted:nth-child(5) > .mat-checkbox')
const settingsUpdated = ('#toast-container > .ng-trigger')

const centerTags = ('.mat-menu-content > :nth-child(9) > .item')
const bodyTags = ('body > sc-app-root > sc-center > sc-app-layout > div > section')
const addTags = ('button')